Final Task: "Library DB".
ilya-frolov/freeit_Lib_DB pull request #1
Opened 2022-09-06 17:36 UTC by ilya-frolov

First draft.

2022-09-08 09:24 UTC, RomanKashenok requested changes

2022-09-08 09:24 UTC, RomanKashenok commented on HomeWork_LibraryDB/library.sql
> +  `name` varchar(255) DEFAULT '0',
по умолчанию ноль? налл ставь

2022-09-08 09:24 UTC, RomanKashenok commented on HomeWork_LibraryDB/library.sql
> +  `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '0',
тоже налл

2022-09-08 09:24 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Author.java
> +    public static Author getAuthorByID(int id) throws SQLException {
не может автор сам себя по айди взять. Вообще классы автора, книги и жанра - это pojo классы - в них не долджно быть никакой логики - они только носители информации

2022-09-08 09:24 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Author.java
> +    @Override
еще qeuals and hashCode

2022-09-08 09:24 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/ConnectionToDB.java
> +                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library", "root", "root");
вынеси креды в константы

2022-09-08 09:24 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/ConnectionToDB.java
> +        static Connection con;
давай сделаем лист коннекшнов, что б не одно тольк соединение на всех было

2022-09-08 09:24 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/ConnectionToDB.java
> +        static Statement postman;
схера ли вы все его почтальоном называете? я просто для примера так назвал, что б ассоциировать с кем-то кто приносит данные

2022-09-08 09:24 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Genre.java
> +    public static Genre getGenreByID(int id) throws SQLException {
убирай отсюда

2022-09-08 09:24 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Library.java
> +    private final Map<String, ArrayList<Book>> books = new TreeMap();
мы больше не храним книги в памяти - убирай

2022-09-08 09:24 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Library.java
> +    public Map<String, ArrayList<Book>> getLibrary() {
больше похоже на метод getAllBooks, но только он должен просто возвращать все книги

2022-09-08 09:24 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Library.java
> +            PreparedStatement ps = ConnectionToDB.con.prepareStatement("insert into books (title, author_id, genre_id) values (?, ?, ?)");
вынеси запросы в константы

2022-09-08 09:24 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Library.java
> +            boolean authorExist = false;
вместо этой проверки почитай про уникальные значения в БД - можно сделать так, что если такой автор в базе есть - он просто не будет снова добавлен (исключение возникнет)

2022-09-08 09:24 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Library.java
> +                        System.out.println("A book with the author " + title + " already exists:");
берешь тайтл, а говоришь что автор есть

2022-09-08 09:24 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Library.java
> +                        PreparedStatement psAuthor = ConnectionToDB.con.prepareStatement("insert into authors (name) values (?)", Statement.RETURN_GENERATED_KEYS);
где-то я эти строки уже видел. Не дублируй, а вынеси все посторяющееся в отдельный метод

2022-09-08 10:39 UTC, ilya-frolov commented on HomeWork_LibraryDB/library.sql
> +  `name` varchar(255) DEFAULT '0',
Точняк. Исправил.

2022-09-08 10:39 UTC, ilya-frolov commented on HomeWork_LibraryDB/library.sql
> +  `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '0',
Исправил

2022-09-08 10:56 UTC, ilya-frolov commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Library.java
> +                        System.out.println("A book with the author " + title + " already exists:");
Исправил.

2022-09-08 13:44 UTC, ilya-frolov commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/ConnectionToDB.java
> +        static Statement postman;
Офигенная ассоциация, мне очень помогла понять. Вот поэтому и используется.

2022-09-09 07:19 UTC, ilya-frolov commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Author.java
> +    public static Author getAuthorByID(int id) throws SQLException {
Исправил.

2022-09-09 07:27 UTC, ilya-frolov commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Author.java
> +    @Override
Добавил.

2022-09-09 07:37 UTC, ilya-frolov commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/ConnectionToDB.java
> +                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library", "root", "root");
Сделано.

2022-09-09 07:38 UTC, ilya-frolov commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Genre.java
> +    public static Genre getGenreByID(int id) throws SQLException {
Убрал.

2022-09-09 08:18 UTC, ilya-frolov commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Library.java
> +    public Map<String, ArrayList<Book>> getLibrary() {
Сделал.

2022-09-09 08:36 UTC, ilya-frolov commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Library.java
> +    private final Map<String, ArrayList<Book>> books = new TreeMap();
Убрал.

2022-09-09 09:02 UTC, ilya-frolov commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Library.java
> +            PreparedStatement ps = ConnectionToDB.con.prepareStatement("insert into books (title, author_id, genre_id) values (?, ?, ?)");
Сделано.

2022-09-09 10:18 UTC, ilya-frolov commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Library.java
> +                        PreparedStatement psAuthor = ConnectionToDB.con.prepareStatement("insert into authors (name) values (?)", Statement.RETURN_GENERATED_KEYS);
Ок.

2022-09-12 14:09 UTC, RomanKashenok requested changes

2022-09-12 14:09 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Author.java
> +    private String authorName;
можно было и просто нейм (он и так в авторе лежит), но и хер с ним

2022-09-12 14:09 UTC, RomanKashenok commented on HomeWork_LibraryDB/library.sql
> +  `name` varchar(255) DEFAULT '0',
исправил и не залил?

2022-09-12 14:09 UTC, RomanKashenok commented on HomeWork_LibraryDB/library.sql
> +  `name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '0',
см. предыдущий )

2022-09-12 14:09 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/ConnectionPool.java
> +        String getPassword();
это можно просто приватными полями задать там, где они используются непосредственно

2022-09-12 14:09 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/ConnectionToDB.java
> +            connectionPool.releaseConnection(con);
а вот это вот зачем? взял конекшн и сразу положил его обратно?

2022-09-12 14:09 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/ConnectionToDB.java
> +public class ConnectionToDB{
я не понимаю вообще назначения этого класса. Вся же логика в DataSourceUtil. Зачем это тут?

2022-09-12 14:09 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/DataSourceUtil.java
> +public class DataSourceUtil implements ConnectionPool {
не знаю где ты это скопировал, но гуд ))

2022-09-12 14:09 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Library.java
> +    private static final PreparedStatement psInsertInGenres, psGetAllGenres, psGetGenreIdByName;
это что такое? несколько вопросов:
1. зачем ты их готовишь на старте приложения? 
2. зачем ты их объявляешь в 3 строки
3. зачем ты их инициализируешь в статик блоке?

2022-09-12 14:09 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Library.java
> +            psGetAllBooks = ConnectionToDB.con.prepareStatement("select * from books");
у тебя есть коннекшн пул, но ты все равно пользуешься единственным коннекшном, который ты там выше создал

2022-09-13 09:42 UTC, ilya-frolov commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Library.java
> +            psGetAllBooks = ConnectionToDB.con.prepareStatement("select * from books");
Вроде исправил.

2022-09-13 09:42 UTC, ilya-frolov commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Library.java
> +    private static final PreparedStatement psInsertInGenres, psGetAllGenres, psGetGenreIdByName;
Уже не актуально

2022-09-13 09:43 UTC, ilya-frolov commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/DataSourceUtil.java
> +public class DataSourceUtil implements ConnectionPool {
По ссылке, которую ты давал.

2022-09-13 09:43 UTC, ilya-frolov commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/ConnectionToDB.java
> +public class ConnectionToDB{
DataSourceUtil дает метод для создания Пула, а в ConnectionToDB я создаю Пул.

2022-09-13 09:43 UTC, ilya-frolov commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/ConnectionToDB.java
> +            connectionPool.releaseConnection(con);
Исправил.

2022-09-13 09:44 UTC, ilya-frolov commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/ConnectionPool.java
> +        String getPassword();
Исправил.

2022-09-13 12:37 UTC, RomanKashenok commented on HomeWork_LibraryDB/library.sql
> +) ENGINE=InnoDB AUTO_INCREMENT=200 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
ебать страх какой 😱

2022-09-13 12:37 UTC, RomanKashenok commented on HomeWork_LibraryDB/library.sql
> +) ENGINE=InnoDB AUTO_INCREMENT=47 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
😱

2022-09-13 12:37 UTC, RomanKashenok commented on HomeWork_LibraryDB/library.sql
> +) ENGINE=InnoDB AUTO_INCREMENT=160 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
😱

2022-09-13 12:37 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/DataSource/Impl/AuthorRepositoryImpl.java
> +    private Connection con;
зачем это тут? убирай

2022-09-13 12:37 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/DataSource/Impl/AuthorRepositoryImpl.java
> +    public ResultSet setAuthorInDB(String authorName) {
неожиданно. Сохраняешь автора, а возвращаешь некий резалт сет.... очень и очень неочевидно

2022-09-13 12:37 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/DataSource/Impl/AuthorRepositoryImpl.java
> +    public ResultSet getAuthorIdByName(String authorName) {
в методе getAuthorIdByName возвращешь не айди...Это как в гаи местном - пошел менять права, а вместо прав дали бумажку, по которой надо что-то сделать (оплатить) и тогда я получу права. Ну не пиздец?

2022-09-13 12:37 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/DataSource/Impl/BookRepositoryImpl.java
> +            } catch (NullPointerException e) {
чета выглядит как говно какое-то...почему мы должны ловить NPE, а не проверять его?

2022-09-13 12:37 UTC, RomanKashenok commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Pojo/Author.java
> +package com.ilyafrolov.LibraryDB.Pojo;
ну по первых - пакеты с маленькой буквы, и что такое pojo? зачем такой пакет? модели, энтити - норм, но не поджо

2022-09-16 07:33 UTC, DimaLamaka requested changes
нигде не закрываешь стейтменты, не закрываешь коннекшены в конекшен пуле при закрытии программы, если делаешь интерфейсы и их имплментацию в репозиториях или сервисах, создай отдельную папку Impl и туда закидывай твою импелментацию, не оперируешь своими кастомными эксепшенами

2022-09-16 07:33 UTC, DimaLamaka commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Genre.java
> +        rs.next();
нет проверки на null, если там не будет жанра с таким id, то будет ошибка

2022-09-16 07:33 UTC, DimaLamaka commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Genre.java
> +        return new Genre(rs.getInt(1), rs.getString(2));
колонки лучше брать по названию, а не по номеру

2022-09-16 07:33 UTC, DimaLamaka commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Library.java
> +        } finally {
убери finally

2022-09-16 07:33 UTC, DimaLamaka commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Genre.java
> +    private String genre;
переименуй поле, что бы не совпадало с именем класса

2022-09-16 07:33 UTC, DimaLamaka commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/Author.java
> +    private String author;
переименуй поле, что бы не совпадало с именем класса

2022-09-16 07:33 UTC, DimaLamaka commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/presentation/Menu.java
> +                        break;
action лишняя, сделай while(true) и при выборе 6 просто печатай сообщение и вызывай return

2022-09-16 07:33 UTC, DimaLamaka commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/presentation/Menu.java
> +                        int id3 = scanner10.nextInt();
зачем создавать кучу сканеров ? почему нельзя создать один?

2022-09-16 07:33 UTC, DimaLamaka commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/database/RepositorySupplier.java
> +}
для чего этот класс?

2022-09-16 07:33 UTC, DimaLamaka commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/database/GenreRepositoryImpl.java
> +            PreparedStatement ps = con.prepareStatement(SQLQuery.GET_FROM_GENRES_BY_ID);
стейтмент не забывай закрывать

2022-09-16 07:33 UTC, DimaLamaka commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/database/GenreRepositoryImpl.java
> +                newGenre = new Genre(rs.getInt(1), rs.getString(2));
лучше конечно брать колонки по названию, а не по номеру

2022-09-16 07:33 UTC, DimaLamaka commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/database/BookRepositoryImpl.java
> +                        RepositorySupplier.getAuthorRepository().getByID(rs.getInt(3)),
репозитории лучше создавай как поля класса и инициализируй их через конструктор

2022-09-16 07:33 UTC, DimaLamaka commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/database/BookRepositoryImpl.java
> +            }
Зачем try в try ? ты отлавливаешь SQLException во внешнем try, убирай

2022-09-16 07:33 UTC, DimaLamaka commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/database/BookRepositoryImpl.java
> +            }
опять же, выше писал

2022-09-16 07:33 UTC, DimaLamaka commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/database/BookRepositoryImpl.java
> +            ps.executeUpdate();
в идеале возвращать кол-во обновленны строк, что бы знать, обновилось что-то или нет

2022-09-16 07:33 UTC, DimaLamaka commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/database/BookRepositoryImpl.java
> +            ps.executeUpdate();
тоже самое что и выше

2022-09-16 07:33 UTC, DimaLamaka commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/database/AuthorRepositoryImpl.java
> +    public Author setInDB(Author author) {
название на add

2022-09-16 07:33 UTC, DimaLamaka commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/database/AuthorRepositoryImpl.java
> +        return author;
если у тебя такая логика, то я бы сначала поискал в базе если такой автор, если есть то вернул его, если нет то добавил бы нового, и не надо было бы отлавливать это исключение

2022-09-16 07:33 UTC, DimaLamaka commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/businesslogic/service/BookServiceImpl.java
> +        }
зачем идти по всем книгам, если просто можно сделать запрос и если есть такая книга, то он обновит её

2022-09-16 07:33 UTC, DimaLamaka commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/businesslogic/service/BookServiceImpl.java
> +        }
тоже самое, что и выше

2022-09-16 07:33 UTC, DimaLamaka commented on HomeWork_LibraryDB/src/com/ilyafrolov/LibraryDB/businesslogic/service/BookServiceImpl.java
> +            }
зачем брать все? если можно вытянуть одну?

2022-09-22 10:02 UTC, closed without merging